name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Update to use the latest version of the action
      - name: Install pnpm
        run: npm install -g pnpm
      - uses: actions/setup-node@v2 # Update to use the latest version of the action
        with:
          node-version: lts/*
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run type-check
      - run: pnpm run lint -- --max-warnings 0
