name: CI

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install bun
        run: curl -LSfs https://raw.githubusercontent.com/tophat/bun/master/scripts/download.sh | bash
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'bun'
      - run: bun install --frozen-lockfile
      - run: bun run type-check
      - run: bun run lint
