name: Lint

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install bun
        run: curl -LSfs https://raw.githubusercontent.com/tophat/bun/master/scripts/download.sh | bash

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Next.js lint
        run: bun run lint | head -n 10
