name: Prettier

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run:
    name: 🤔
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Update to use the latest version of the action
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install pnpm
        run: npm install -g pnpm
      - run: pnpm install --ignore-scripts --only=dev

      - name: check if workflows needs prettier
        run: npx prettier --cache --check ".github/workflows/**/*.yml" || (echo "An action can't make changes to actions, you'll have to run prettier manually" && exit 1)
      - run: npx prettier --ignore-path .gitignore pnpm-lock.yaml --cache --write .
      - name: Commit changes
        run: |
          git config --global user.name 'github_actions'
          git config --global user.email 'github_actions@github.com'
          git add -A
          git commit -m '✨ Prettier formatted ✨' || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}
